[tasks.default]
    links = [
        [".vimrc"],
        [".zshrc"],
	[".gitconfig"],
	[".atom/init.coffee"],
        [".atom/styles.less"],
        [".config/i3/config"],
        [".config/i3status/config"],
        [".config/mc/ini"],
        [".config/mc/panels.ini"],
    ]
